// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewSave(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddNewSave'](arg1, arg2, arg3, arg4);
}

export function AddNewSeason(arg1, arg2) {
  return window['go']['main']['App']['AddNewSeason'](arg1, arg2);
}

export function DeleteSave(arg1) {
  return window['go']['main']['App']['DeleteSave'](arg1);
}

export function GetAllPlayersSeason() {
  return window['go']['main']['App']['GetAllPlayersSeason']();
}

export function GetAllPlayersTotals() {
  return window['go']['main']['App']['GetAllPlayersTotals']();
}

export function GetAllRankings() {
  return window['go']['main']['App']['GetAllRankings']();
}

export function GetAllResults() {
  return window['go']['main']['App']['GetAllResults']();
}

export function GetAllTransfers() {
  return window['go']['main']['App']['GetAllTransfers']();
}

export function GetAllTrophies() {
  return window['go']['main']['App']['GetAllTrophies']();
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetNumSaves() {
  return window['go']['main']['App']['GetNumSaves']();
}

export function GetNumSeasons() {
  return window['go']['main']['App']['GetNumSeasons']();
}

export function GetNumSeasonsInSave(arg1) {
  return window['go']['main']['App']['GetNumSeasonsInSave'](arg1);
}

export function GetSaveHomeRankings(arg1) {
  return window['go']['main']['App']['GetSaveHomeRankings'](arg1);
}

export function GetSavePlayers(arg1) {
  return window['go']['main']['App']['GetSavePlayers'](arg1);
}

export function GetSavePlayersTotals(arg1) {
  return window['go']['main']['App']['GetSavePlayersTotals'](arg1);
}

export function GetSaveResults(arg1) {
  return window['go']['main']['App']['GetSaveResults'](arg1);
}

export function GetSaveStory(arg1) {
  return window['go']['main']['App']['GetSaveStory'](arg1);
}

export function GetSaveTransfers(arg1) {
  return window['go']['main']['App']['GetSaveTransfers'](arg1);
}

export function GetSinglePlayer(arg1) {
  return window['go']['main']['App']['GetSinglePlayer'](arg1);
}

export function GetTrophies(arg1) {
  return window['go']['main']['App']['GetTrophies'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function RetrieveSaves() {
  return window['go']['main']['App']['RetrieveSaves']();
}

export function SelectFileParse(arg1) {
  return window['go']['main']['App']['SelectFileParse'](arg1);
}

export function SelectNewTrophyImage(arg1) {
  return window['go']['main']['App']['SelectNewTrophyImage'](arg1);
}

export function SingleImage(arg1) {
  return window['go']['main']['App']['SingleImage'](arg1);
}

export function SingleSave(arg1) {
  return window['go']['main']['App']['SingleSave'](arg1);
}

export function UpdateSaveStory(arg1) {
  return window['go']['main']['App']['UpdateSaveStory'](arg1);
}

export function UploadSaveImage(arg1) {
  return window['go']['main']['App']['UploadSaveImage'](arg1);
}
