name: Wails build

on:
  workflow_dispatch:
  push:
    tags:
      # Match any new tag
      - "v*"
env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name:"Save Tracker",
            platform:linux/amd64,
            os:ubuntu-latest
          - name:"Save Tracker",
            platform:windows/amd64,
            os:windows-latest
          - name:"Save Tracker",
            platform:darwin/universal,
            os:macos-latest
            
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get Go Version
        run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV

      - name: Get Save Tracker product version
        run: echo "PROJECT_VERSION=$(jq .Info.productVersion wails.json)" >> $GITHUB_ENV

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: $GO_VERSION
